import Head from 'next/head';
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Doodle Freaks",
  
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
      
      <link rel="icon" href="/favicon.ico" />
</Head>
      <body className={inter.className}>
        <Navbar className=" " />
        {children}
      </body>
    </html>
  );
}